/**
 * AUTO-GENERATED by scripts/write-version.mjs during builds.
 * Safe to commit; deploy builds overwrite these values.
 */
export const APP_VERSION_INFO = {
  /** Semver from package.json */
  version: "1.0.0",
  /** Increments on each GitHub Actions deploy (run number); "dev" locally */
  buildNumber: "dev",
  /** ISO timestamp of when this bundle was built */
  builtAt: "2026-07-25T19:03:44.678Z",
} as const;
