/**
 * AUTO-GENERATED by scripts/write-version.mjs during builds.
 * Safe to commit; deploy builds overwrite these values.
 */
export interface AppVersionInfo {
  version: string;
  buildNumber: string;
  builtAt: string;
}

export const APP_VERSION_INFO: AppVersionInfo = {
  version: "1.0.0",
  buildNumber: "dev",
  builtAt: "2026-07-25T19:25:48.124Z",
};
