import { writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const packageJson = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

const version = String(packageJson.version ?? '0.0.0');
const buildNumber =
  process.env.APP_BUILD_NUMBER ||
  process.env.GITHUB_RUN_NUMBER ||
  'dev';
const builtAt = new Date().toISOString();

const contents = `/**
 * AUTO-GENERATED by scripts/write-version.mjs during builds.
 * Safe to commit; deploy builds overwrite these values.
 */
export const APP_VERSION_INFO = {
  /** Semver from package.json */
  version: ${JSON.stringify(version)},
  /** Increments on each GitHub Actions deploy (run number); "dev" locally */
  buildNumber: ${JSON.stringify(String(buildNumber))},
  /** ISO timestamp of when this bundle was built */
  builtAt: ${JSON.stringify(builtAt)},
} as const;
`;

const outPath = join(root, 'src', 'app', 'version.ts');
writeFileSync(outPath, contents, 'utf8');
console.log(`Wrote ${outPath} (version=${version}, build=${buildNumber})`);
